logging:
  level:
    org: WARN

server:
  port: ${PORT}

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVER_URI}

spring:
  datasource:
    url: ${DB_URI}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: false
  security:
    user:
      name: ${SPRING_SECURITY_USER}
      password: ${SPRING_SECURITY_PASS}
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASS}
    template:
      retry:
        enabled: true
        initial-interval: 2s
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 5s
          max-attempts: 10
          max-interval: 20s
          multiplier: 2


# custom defined properties below

jwt_secret: ${JWT_SECRET}
salt_rounds: ${SALT_ROUNDS}

rabbitmq:
    queue:
      dead-letter: queue.dead