spring:
  profiles:
    active:
    - prod
  application:
    name: discovery-server

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF